// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: holiday.proto

package test

import (
	_ "github.com/emicklei/protocheck"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Holiday struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// per field check
	Destination string    `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Group       []*Person `protobuf:"bytes,2,rep,name=group,proto3" json:"group,omitempty"`
}

func (x *Holiday) Reset() {
	*x = Holiday{}
	mi := &file_holiday_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holiday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holiday) ProtoMessage() {}

func (x *Holiday) ProtoReflect() protoreflect.Message {
	mi := &file_holiday_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holiday.ProtoReflect.Descriptor instead.
func (*Holiday) Descriptor() ([]byte, []int) {
	return file_holiday_proto_rawDescGZIP(), []int{0}
}

func (x *Holiday) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Holiday) GetGroup() []*Person {
	if x != nil {
		return x.Group
	}
	return nil
}

var File_holiday_proto protoreflect.FileDescriptor

var file_holiday_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x1a, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x90, 0x01, 0x0a, 0x07, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x12, 0x43, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x21, 0xa2, 0xdc, 0xb4, 0x4c, 0x1c, 0x1a, 0x1a, 0x73, 0x69, 0x7a, 0x65, 0x28,
	0x74, 0x68, 0x69, 0x73, 0x2e, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x29, 0x20, 0x3e, 0x20, 0x31, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x42, 0x1b, 0xa2, 0xdc, 0xb4, 0x4c, 0x16, 0x1a, 0x14, 0x73, 0x69, 0x7a, 0x65, 0x28, 0x74, 0x68,
	0x69, 0x73, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x29, 0x20, 0x3e, 0x20, 0x30, 0x52, 0x05, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x65, 0x6d, 0x69, 0x63, 0x6b, 0x6c, 0x65, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x3b, 0x74, 0x65, 0x73, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_holiday_proto_rawDescOnce sync.Once
	file_holiday_proto_rawDescData = file_holiday_proto_rawDesc
)

func file_holiday_proto_rawDescGZIP() []byte {
	file_holiday_proto_rawDescOnce.Do(func() {
		file_holiday_proto_rawDescData = protoimpl.X.CompressGZIP(file_holiday_proto_rawDescData)
	})
	return file_holiday_proto_rawDescData
}

var file_holiday_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_holiday_proto_goTypes = []any{
	(*Holiday)(nil), // 0: check.Holiday
	(*Person)(nil),  // 1: check.Person
}
var file_holiday_proto_depIdxs = []int32{
	1, // 0: check.Holiday.group:type_name -> check.Person
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_holiday_proto_init() }
func file_holiday_proto_init() {
	if File_holiday_proto != nil {
		return
	}
	file_person_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_holiday_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_holiday_proto_goTypes,
		DependencyIndexes: file_holiday_proto_depIdxs,
		MessageInfos:      file_holiday_proto_msgTypes,
	}.Build()
	File_holiday_proto = out.File
	file_holiday_proto_rawDesc = nil
	file_holiday_proto_goTypes = nil
	file_holiday_proto_depIdxs = nil
}
