// Copyright (c) 2024 Ernest Micklei

// MIT License

// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and associated documentation files (the
// "Software"), to deal in the Software without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so, subject to
// the following conditions:

// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
// LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
// OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: check.proto

package protocheck

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Check struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // optional identifier for lookup purposes
	Fail          string                 `protobuf:"bytes,2,opt,name=fail,proto3" json:"fail,omitempty"` // optional message to report when the check fails
	Cel           string                 `protobuf:"bytes,3,opt,name=cel,proto3" json:"cel,omitempty"`   // Google/CEL expression (https://github.com/google/cel-spec)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check) Reset() {
	*x = Check{}
	mi := &file_check_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_check_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_check_proto_rawDescGZIP(), []int{0}
}

func (x *Check) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Check) GetFail() string {
	if x != nil {
		return x.Fail
	}
	return ""
}

func (x *Check) GetCel() string {
	if x != nil {
		return x.Cel
	}
	return ""
}

type CheckError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // optional id of the check that failed
	Fail          string                 `protobuf:"bytes,2,opt,name=fail,proto3" json:"fail,omitempty"` // optional message to display
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"` // path to the field name that failed, if empty then it was a message check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckError) Reset() {
	*x = CheckError{}
	mi := &file_check_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckError) ProtoMessage() {}

func (x *CheckError) ProtoReflect() protoreflect.Message {
	mi := &file_check_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckError.ProtoReflect.Descriptor instead.
func (*CheckError) Descriptor() ([]byte, []int) {
	return file_check_proto_rawDescGZIP(), []int{1}
}

func (x *CheckError) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckError) GetFail() string {
	if x != nil {
		return x.Fail
	}
	return ""
}

func (x *CheckError) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var file_check_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]*Check)(nil),
		Field:         20030916,
		Name:          "check.message",
		Tag:           "bytes,20030916,rep,name=message",
		Filename:      "check.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]*Check)(nil),
		Field:         20030916,
		Name:          "check.field",
		Tag:           "bytes,20030916,rep,name=field",
		Filename:      "check.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// repeated check.Check message = 20030916;
	E_Message = &file_check_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// repeated check.Check field = 20030916;
	E_Field = &file_check_proto_extTypes[1]
)

var File_check_proto protoreflect.FileDescriptor

const file_check_proto_rawDesc = "" +
	"\n" +
	"\vcheck.proto\x12\x05check\x1a google/protobuf/descriptor.proto\"=\n" +
	"\x05Check\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04fail\x18\x02 \x01(\tR\x04fail\x12\x10\n" +
	"\x03cel\x18\x03 \x01(\tR\x03cel\"D\n" +
	"\n" +
	"CheckError\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04fail\x18\x02 \x01(\tR\x04fail\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path:J\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xc4\xcb\xc6\t \x03(\v2\f.check.CheckR\amessage:D\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xc4\xcb\xc6\t \x03(\v2\f.check.CheckR\x05fieldBV\n" +
	"\x1aorg.emicklei.protocheck.pbB\vCheckProtosP\x01Z)github.com/emicklei/protocheck;protocheckb\x06proto3"

var (
	file_check_proto_rawDescOnce sync.Once
	file_check_proto_rawDescData []byte
)

func file_check_proto_rawDescGZIP() []byte {
	file_check_proto_rawDescOnce.Do(func() {
		file_check_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_check_proto_rawDesc), len(file_check_proto_rawDesc)))
	})
	return file_check_proto_rawDescData
}

var file_check_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_check_proto_goTypes = []any{
	(*Check)(nil),                       // 0: check.Check
	(*CheckError)(nil),                  // 1: check.CheckError
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 3: google.protobuf.FieldOptions
}
var file_check_proto_depIdxs = []int32{
	2, // 0: check.message:extendee -> google.protobuf.MessageOptions
	3, // 1: check.field:extendee -> google.protobuf.FieldOptions
	0, // 2: check.message:type_name -> check.Check
	0, // 3: check.field:type_name -> check.Check
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_check_proto_init() }
func file_check_proto_init() {
	if File_check_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_check_proto_rawDesc), len(file_check_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_check_proto_goTypes,
		DependencyIndexes: file_check_proto_depIdxs,
		MessageInfos:      file_check_proto_msgTypes,
		ExtensionInfos:    file_check_proto_extTypes,
	}.Build()
	File_check_proto = out.File
	file_check_proto_goTypes = nil
	file_check_proto_depIdxs = nil
}
