// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person.proto
// Protobuf Java Version: 4.32.0

package hr;

@com.google.protobuf.Generated
public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:golang.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * with per field state checks
   * </pre>
   *
   * <code>string name = 1 [(.check.field) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * with per field state checks
   * </pre>
   *
   * <code>string name = 1 [(.check.field) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string middle_name = 2 [(.check.field) = { ... }</code>
   * @return Whether the middleName field is set.
   */
  boolean hasMiddleName();
  /**
   * <code>optional string middle_name = 2 [(.check.field) = { ... }</code>
   * @return The middleName.
   */
  java.lang.String getMiddleName();
  /**
   * <code>optional string middle_name = 2 [(.check.field) = { ... }</code>
   * @return The bytes for middleName.
   */
  com.google.protobuf.ByteString
      getMiddleNameBytes();

  /**
   * <code>string surname = 3 [(.check.field) = { ... }</code>
   * @return The surname.
   */
  java.lang.String getSurname();
  /**
   * <code>string surname = 3 [(.check.field) = { ... }</code>
   * @return The bytes for surname.
   */
  com.google.protobuf.ByteString
      getSurnameBytes();

  /**
   * <code>.google.protobuf.Timestamp birth_date = 4 [(.check.field) = { ... }</code>
   * @return Whether the birthDate field is set.
   */
  boolean hasBirthDate();
  /**
   * <code>.google.protobuf.Timestamp birth_date = 4 [(.check.field) = { ... }</code>
   * @return The birthDate.
   */
  com.google.protobuf.Timestamp getBirthDate();
  /**
   * <code>.google.protobuf.Timestamp birth_date = 4 [(.check.field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getBirthDateOrBuilder();

  /**
   * <code>.golang.Person.Health health = 5;</code>
   * @return Whether the health field is set.
   */
  boolean hasHealth();
  /**
   * <code>.golang.Person.Health health = 5;</code>
   * @return The health.
   */
  hr.Person.Health getHealth();
  /**
   * <code>.golang.Person.Health health = 5;</code>
   */
  hr.Person.HealthOrBuilder getHealthOrBuilder();

  /**
   * <code>string email = 6 [(.check.field) = { ... }</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>string email = 6 [(.check.field) = { ... }</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 6 [(.check.field) = { ... }</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string phone = 7 [(.check.field) = { ... }</code>
   * @return Whether the phone field is set.
   */
  boolean hasPhone();
  /**
   * <code>string phone = 7 [(.check.field) = { ... }</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 7 [(.check.field) = { ... }</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <pre>
   * repeated with field check
   * </pre>
   *
   * <code>repeated string nicknames = 8 [(.check.field) = { ... }</code>
   * @return A list containing the nicknames.
   */
  java.util.List<java.lang.String>
      getNicknamesList();
  /**
   * <pre>
   * repeated with field check
   * </pre>
   *
   * <code>repeated string nicknames = 8 [(.check.field) = { ... }</code>
   * @return The count of nicknames.
   */
  int getNicknamesCount();
  /**
   * <pre>
   * repeated with field check
   * </pre>
   *
   * <code>repeated string nicknames = 8 [(.check.field) = { ... }</code>
   * @param index The index of the element to return.
   * @return The nicknames at the given index.
   */
  java.lang.String getNicknames(int index);
  /**
   * <pre>
   * repeated with field check
   * </pre>
   *
   * <code>repeated string nicknames = 8 [(.check.field) = { ... }</code>
   * @param index The index of the value to return.
   * @return The bytes of the nicknames at the given index.
   */
  com.google.protobuf.ByteString
      getNicknamesBytes(int index);

  /**
   * <pre>
   * repeated proto message with  check
   * </pre>
   *
   * <code>repeated .golang.Pet pets = 9 [(.check.field) = { ... }</code>
   */
  java.util.List<hr.Pet> 
      getPetsList();
  /**
   * <pre>
   * repeated proto message with  check
   * </pre>
   *
   * <code>repeated .golang.Pet pets = 9 [(.check.field) = { ... }</code>
   */
  hr.Pet getPets(int index);
  /**
   * <pre>
   * repeated proto message with  check
   * </pre>
   *
   * <code>repeated .golang.Pet pets = 9 [(.check.field) = { ... }</code>
   */
  int getPetsCount();
  /**
   * <pre>
   * repeated proto message with  check
   * </pre>
   *
   * <code>repeated .golang.Pet pets = 9 [(.check.field) = { ... }</code>
   */
  java.util.List<? extends hr.PetOrBuilder> 
      getPetsOrBuilderList();
  /**
   * <pre>
   * repeated proto message with  check
   * </pre>
   *
   * <code>repeated .golang.Pet pets = 9 [(.check.field) = { ... }</code>
   */
  hr.PetOrBuilder getPetsOrBuilder(
      int index);

  /**
   * <pre>
   * map with field check
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 10 [(.check.field) = { ... }</code>
   */
  int getAttributesCount();
  /**
   * <pre>
   * map with field check
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 10 [(.check.field) = { ... }</code>
   */
  boolean containsAttributes(
      java.lang.String key);
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAttributes();
  /**
   * <pre>
   * map with field check
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 10 [(.check.field) = { ... }</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAttributesMap();
  /**
   * <pre>
   * map with field check
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 10 [(.check.field) = { ... }</code>
   */
  /* nullable */
java.lang.String getAttributesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * map with field check
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 10 [(.check.field) = { ... }</code>
   */
  java.lang.String getAttributesOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * map with proto message value with check
   * </pre>
   *
   * <code>map&lt;string, .golang.Pet&gt; favorites = 11 [(.check.field) = { ... }</code>
   */
  int getFavoritesCount();
  /**
   * <pre>
   * map with proto message value with check
   * </pre>
   *
   * <code>map&lt;string, .golang.Pet&gt; favorites = 11 [(.check.field) = { ... }</code>
   */
  boolean containsFavorites(
      java.lang.String key);
  /**
   * Use {@link #getFavoritesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, hr.Pet>
  getFavorites();
  /**
   * <pre>
   * map with proto message value with check
   * </pre>
   *
   * <code>map&lt;string, .golang.Pet&gt; favorites = 11 [(.check.field) = { ... }</code>
   */
  java.util.Map<java.lang.String, hr.Pet>
  getFavoritesMap();
  /**
   * <pre>
   * map with proto message value with check
   * </pre>
   *
   * <code>map&lt;string, .golang.Pet&gt; favorites = 11 [(.check.field) = { ... }</code>
   */
  /* nullable */
hr.Pet getFavoritesOrDefault(
      java.lang.String key,
      /* nullable */
hr.Pet defaultValue);
  /**
   * <pre>
   * map with proto message value with check
   * </pre>
   *
   * <code>map&lt;string, .golang.Pet&gt; favorites = 11 [(.check.field) = { ... }</code>
   */
  hr.Pet getFavoritesOrThrow(
      java.lang.String key);

  /**
   * <code>.google.protobuf.Timestamp no_check_date = 12;</code>
   * @return Whether the noCheckDate field is set.
   */
  boolean hasNoCheckDate();
  /**
   * <code>.google.protobuf.Timestamp no_check_date = 12;</code>
   * @return The noCheckDate.
   */
  com.google.protobuf.Timestamp getNoCheckDate();
  /**
   * <code>.google.protobuf.Timestamp no_check_date = 12;</code>
   */
  com.google.protobuf.TimestampOrBuilder getNoCheckDateOrBuilder();

  /**
   * <code>.golang.Person.Gender gender = 13;</code>
   * @return The enum numeric value on the wire for gender.
   */
  int getGenderValue();
  /**
   * <code>.golang.Person.Gender gender = 13;</code>
   * @return The gender.
   */
  hr.Person.Gender getGender();

  hr.Person.IdentificationCase getIdentificationCase();
}
