// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person.proto
// Protobuf Java Version: 4.29.3

package hr;

public interface PetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:golang.Pet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string kind = 1 [(.check.field) = { ... }</code>
   * @return The kind.
   */
  java.lang.String getKind();
  /**
   * <code>string kind = 1 [(.check.field) = { ... }</code>
   * @return The bytes for kind.
   */
  com.google.protobuf.ByteString
      getKindBytes();

  /**
   * <code>string name = 2 [(.check.field) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [(.check.field) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
