// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: check.proto
// Protobuf Java Version: 4.29.3

package org.emicklei.protocheck.pb;

public interface CheckErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:check.CheckError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * optional id of the check that failed
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * optional id of the check that failed
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * optional message to display
   * </pre>
   *
   * <code>string fail = 2;</code>
   * @return The fail.
   */
  java.lang.String getFail();
  /**
   * <pre>
   * optional message to display
   * </pre>
   *
   * <code>string fail = 2;</code>
   * @return The bytes for fail.
   */
  com.google.protobuf.ByteString
      getFailBytes();

  /**
   * <pre>
   * path to the field that failed, if empty then the field is part of the root message
   * </pre>
   *
   * <code>string path = 3;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <pre>
   * path to the field that failed, if empty then the field is part of the root message
   * </pre>
   *
   * <code>string path = 3;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();
}
