// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: check.proto
// Protobuf Java Version: 4.29.3

package org.emicklei.protocheck.pb;

public interface CheckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:check.Check)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * optional identifier for lookup purposes
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * optional identifier for lookup purposes
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * optional message to report when the check fails
   * </pre>
   *
   * <code>string fail = 2;</code>
   * @return The fail.
   */
  java.lang.String getFail();
  /**
   * <pre>
   * optional message to report when the check fails
   * </pre>
   *
   * <code>string fail = 2;</code>
   * @return The bytes for fail.
   */
  com.google.protobuf.ByteString
      getFailBytes();

  /**
   * <pre>
   * Google/CEL expression (https://github.com/google/cel-spec)
   * </pre>
   *
   * <code>string cel = 3;</code>
   * @return The cel.
   */
  java.lang.String getCel();
  /**
   * <pre>
   * Google/CEL expression (https://github.com/google/cel-spec)
   * </pre>
   *
   * <code>string cel = 3;</code>
   * @return The bytes for cel.
   */
  com.google.protobuf.ByteString
      getCelBytes();
}
