// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: toy.proto

package golang

import (
	_ "github.com/emicklei/protocheck"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Toy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Toy) Reset() {
	*x = Toy{}
	mi := &file_toy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Toy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toy) ProtoMessage() {}

func (x *Toy) ProtoReflect() protoreflect.Message {
	mi := &file_toy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toy.ProtoReflect.Descriptor instead.
func (*Toy) Descriptor() ([]byte, []int) {
	return file_toy_proto_rawDescGZIP(), []int{0}
}

func (x *Toy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Toy) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

var File_toy_proto protoreflect.FileDescriptor

const file_toy_proto_rawDesc = "" +
	"\n" +
	"\ttoy.proto\x12\x06golang\x1a\vcheck.proto\"d\n" +
	"\x03Toy\x12,\n" +
	"\x04name\x18\x01 \x01(\tB\x18\xa2ܴL\x13\x1a\x11size(this.name)>0R\x04name\x12/\n" +
	"\x05color\x18\x02 \x01(\tB\x19\xa2ܴL\x14\x1a\x12size(this.color)>0R\x05colorBF\n" +
	"\x02hrB\bHRProtosP\x01Z4github.com/emicklei/protocheck-example/golang;golangb\x06proto3"

var (
	file_toy_proto_rawDescOnce sync.Once
	file_toy_proto_rawDescData []byte
)

func file_toy_proto_rawDescGZIP() []byte {
	file_toy_proto_rawDescOnce.Do(func() {
		file_toy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_toy_proto_rawDesc), len(file_toy_proto_rawDesc)))
	})
	return file_toy_proto_rawDescData
}

var file_toy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_toy_proto_goTypes = []any{
	(*Toy)(nil), // 0: golang.Toy
}
var file_toy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_toy_proto_init() }
func file_toy_proto_init() {
	if File_toy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_toy_proto_rawDesc), len(file_toy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_toy_proto_goTypes,
		DependencyIndexes: file_toy_proto_depIdxs,
		MessageInfos:      file_toy_proto_msgTypes,
	}.Build()
	File_toy_proto = out.File
	file_toy_proto_goTypes = nil
	file_toy_proto_depIdxs = nil
}
